/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.ConectarBase;
import Clases.GeneraCodigo;
import Clases.Querys;
import static Ventanas.VtnHome.con;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class VtnAGestionEmpleados extends javax.swing.JFrame
{

    int xy, xx;
    ArrayList<Object> columnaMap1 = new ArrayList();
    ArrayList<Object> columnaMap2 = new ArrayList();
    ArrayList<Object> columnaMap3 = new ArrayList();
    Querys q;
    boolean flag = true;

    /**
     * Creates new form VtnAGestionSucursal
     */
    public VtnAGestionEmpleados()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPTop = new javax.swing.JPanel();
        exit2 = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        jLGestion = new javax.swing.JLabel();
        jPMiddle = new javax.swing.JPanel();
        jLID = new javax.swing.JLabel();
        jTFID = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jSNombre = new javax.swing.JSeparator();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLAPaterno = new javax.swing.JLabel();
        jTFAPaterno = new javax.swing.JTextField();
        jSAPaterno = new javax.swing.JSeparator();
        jLNAMaterno = new javax.swing.JLabel();
        jTFAMaterno = new javax.swing.JTextField();
        jSAMaterno = new javax.swing.JSeparator();
        jPBottom = new javax.swing.JPanel();
        jLSucursal = new javax.swing.JLabel();
        jCBSucursal = new javax.swing.JComboBox<>();
        jLSexo = new javax.swing.JLabel();
        jLFechaNac = new javax.swing.JLabel();
        jTFFechaNac = new javax.swing.JTextField();
        jSFechaNac = new javax.swing.JSeparator();
        jLEstado = new javax.swing.JLabel();
        jTFCurp = new javax.swing.JTextField();
        jSEstado = new javax.swing.JSeparator();
        jLTelefono = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jSTelefono = new javax.swing.JSeparator();
        jLTipoEmple = new javax.swing.JLabel();
        jCBTipoEmple = new javax.swing.JComboBox<>();
        jLCorreo = new javax.swing.JLabel();
        jTFCorreo = new javax.swing.JTextField();
        jSCorreo = new javax.swing.JSeparator();
        jLContra = new javax.swing.JLabel();
        jSContra = new javax.swing.JSeparator();
        jLFechaAlta = new javax.swing.JLabel();
        jTFFechaAlta = new javax.swing.JTextField();
        jSFechaAlta = new javax.swing.JSeparator();
        jPFContra = new javax.swing.JPasswordField();
        jCBSexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsulta = new javax.swing.JTable();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1368, 744));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPTop.setBackground(new java.awt.Color(255, 255, 255));
        jPTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                jPTopMouseDragged(evt);
            }
        });
        jPTop.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPTopMousePressed(evt);
            }
        });
        jPTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        exit2.setForeground(new java.awt.Color(139, 157, 195));
        exit2.setText("_");
        exit2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                exit2MousePressed(evt);
            }
        });
        jPTop.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1288, 8, 32, 32));

        exit3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit3.setForeground(new java.awt.Color(139, 157, 195));
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                exit3MousePressed(evt);
            }
        });
        jPTop.add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 8, 48, 32));

        jLGestion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLGestion.setForeground(new java.awt.Color(139, 157, 195));
        jLGestion.setText("Gestion de empleados");
        jPTop.add(jLGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, -1, -1));

        getContentPane().add(jPTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1368, 56));

        jPMiddle.setBackground(new java.awt.Color(139, 157, 195));
        jPMiddle.setForeground(new java.awt.Color(255, 255, 255));
        jPMiddle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLID.setForeground(new java.awt.Color(255, 255, 255));
        jLID.setText("ID: ");
        jPMiddle.add(jLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 16, -1, -1));

        jTFID.setBackground(new java.awt.Color(139, 157, 195));
        jTFID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFID.setForeground(new java.awt.Color(255, 255, 255));
        jTFID.setBorder(null);
        jTFID.setEnabled(false);
        jPMiddle.add(jTFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 16, 224, 24));

        jTFNombre.setBackground(new java.awt.Color(139, 157, 195));
        jTFNombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTFNombre.setBorder(null);
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFNombreKeyTyped(evt);
            }
        });
        jPMiddle.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 48, 224, 24));

        jLNombre.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre: ");
        jPMiddle.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 48, -1, -1));
        jPMiddle.add(jSNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 72, 224, 16));

        jBGuardar.setBackground(new java.awt.Color(247, 247, 247));
        jBGuardar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(139, 157, 195));
        jBGuardar.setText("Guardar");
        jBGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 227, 238)));
        jBGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBGuardarActionPerformed(evt);
            }
        });
        jBGuardar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jBGuardarKeyPressed(evt);
            }
        });
        jPMiddle.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1096, 64, 88, 32));

        jBCancelar.setBackground(new java.awt.Color(247, 247, 247));
        jBCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(139, 157, 195));
        jBCancelar.setText("Cancelar");
        jBCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 227, 238)));
        jBCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBCancelarActionPerformed(evt);
            }
        });
        jPMiddle.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1208, 64, 88, 32));

        jLAPaterno.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLAPaterno.setForeground(new java.awt.Color(255, 255, 255));
        jLAPaterno.setText("Apellido paterno:");
        jPMiddle.add(jLAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 80, -1, -1));

        jTFAPaterno.setBackground(new java.awt.Color(139, 157, 195));
        jTFAPaterno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFAPaterno.setForeground(new java.awt.Color(255, 255, 255));
        jTFAPaterno.setBorder(null);
        jTFAPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFAPaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFAPaternoKeyTyped(evt);
            }
        });
        jPMiddle.add(jTFAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 80, 224, 24));
        jPMiddle.add(jSAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 104, 224, 16));

        jLNAMaterno.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLNAMaterno.setForeground(new java.awt.Color(255, 255, 255));
        jLNAMaterno.setText("Apellido materno: ");
        jPMiddle.add(jLNAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 112, -1, -1));

        jTFAMaterno.setBackground(new java.awt.Color(139, 157, 195));
        jTFAMaterno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFAMaterno.setForeground(new java.awt.Color(255, 255, 255));
        jTFAMaterno.setBorder(null);
        jTFAMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFAMaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFAMaternoKeyTyped(evt);
            }
        });
        jPMiddle.add(jTFAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 112, 224, 24));
        jPMiddle.add(jSAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 136, 224, 16));

        getContentPane().add(jPMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 1368, 168));

        jPBottom.setBackground(new java.awt.Color(255, 255, 255));
        jPBottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLSucursal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLSucursal.setForeground(new java.awt.Color(139, 157, 195));
        jLSucursal.setText("Sucursal: ");
        jPBottom.add(jLSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 40, -1, -1));

        jCBSucursal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCBSucursal.setForeground(new java.awt.Color(139, 157, 195));
        jCBSucursal.setBorder(null);
        jCBSucursal.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jCBSucursalKeyPressed(evt);
            }
        });
        jPBottom.add(jCBSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 40, 208, 24));

        jLSexo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLSexo.setForeground(new java.awt.Color(139, 157, 195));
        jLSexo.setText("Sexo: ");
        jPBottom.add(jLSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 80, -1, -1));

        jLFechaNac.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLFechaNac.setForeground(new java.awt.Color(139, 157, 195));
        jLFechaNac.setText("Fecha de nacimiento: ");
        jPBottom.add(jLFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 120, -1, -1));

        jTFFechaNac.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFFechaNac.setForeground(new java.awt.Color(139, 157, 195));
        jTFFechaNac.setBorder(null);
        jTFFechaNac.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFFechaNacKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFFechaNacKeyTyped(evt);
            }
        });
        jPBottom.add(jTFFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 120, 208, -1));

        jSFechaNac.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 144, 208, 16));

        jLEstado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(139, 157, 195));
        jLEstado.setText("CURP: ");
        jPBottom.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 160, -1, -1));

        jTFCurp.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFCurp.setForeground(new java.awt.Color(139, 157, 195));
        jTFCurp.setBorder(null);
        jTFCurp.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFCurpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFCurpKeyTyped(evt);
            }
        });
        jPBottom.add(jTFCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 160, 208, -1));

        jSEstado.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 184, 208, 16));

        jLTelefono.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLTelefono.setForeground(new java.awt.Color(139, 157, 195));
        jLTelefono.setText("Telefono: ");
        jPBottom.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 200, -1, -1));

        jTFTelefono.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(139, 157, 195));
        jTFTelefono.setBorder(null);
        jTFTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFTelefonoKeyTyped(evt);
            }
        });
        jPBottom.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 200, 208, -1));

        jSTelefono.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 224, 208, 16));

        jLTipoEmple.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLTipoEmple.setForeground(new java.awt.Color(139, 157, 195));
        jLTipoEmple.setText("Tipo de empleado: ");
        jPBottom.add(jLTipoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 248, -1, -1));

        jCBTipoEmple.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCBTipoEmple.setForeground(new java.awt.Color(139, 157, 195));
        jCBTipoEmple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Vendedor" }));
        jCBTipoEmple.setBorder(null);
        jCBTipoEmple.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jCBTipoEmpleKeyPressed(evt);
            }
        });
        jPBottom.add(jCBTipoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 248, 208, 24));

        jLCorreo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLCorreo.setForeground(new java.awt.Color(139, 157, 195));
        jLCorreo.setText("Correo: ");
        jPBottom.add(jLCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 288, -1, -1));

        jTFCorreo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFCorreo.setForeground(new java.awt.Color(139, 157, 195));
        jTFCorreo.setBorder(null);
        jTFCorreo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTFCorreoActionPerformed(evt);
            }
        });
        jTFCorreo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFCorreoKeyTyped(evt);
            }
        });
        jPBottom.add(jTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 288, 208, -1));

        jSCorreo.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 312, 208, 16));

        jLContra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLContra.setForeground(new java.awt.Color(139, 157, 195));
        jLContra.setText("Contraseña: ");
        jPBottom.add(jLContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 328, -1, -1));

        jSContra.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 352, 208, 16));

        jLFechaAlta.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLFechaAlta.setForeground(new java.awt.Color(139, 157, 195));
        jLFechaAlta.setText("Fecha de alta: ");
        jPBottom.add(jLFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 368, -1, -1));

        jTFFechaAlta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFFechaAlta.setForeground(new java.awt.Color(139, 157, 195));
        jTFFechaAlta.setBorder(null);
        jTFFechaAlta.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFFechaAltaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFFechaAltaKeyTyped(evt);
            }
        });
        jPBottom.add(jTFFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 368, 208, -1));

        jSFechaAlta.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 392, 208, 16));

        jPFContra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPFContra.setForeground(new java.awt.Color(139, 157, 195));
        jPFContra.setToolTipText("");
        jPFContra.setBorder(null);
        jPFContra.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jPFContraKeyPressed(evt);
            }
        });
        jPBottom.add(jPFContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 328, 208, -1));

        jCBSexo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCBSexo.setForeground(new java.awt.Color(139, 157, 195));
        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jCBSexo.setBorder(null);
        jCBSexo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jCBSexoKeyPressed(evt);
            }
        });
        jPBottom.add(jCBSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 80, 208, 24));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTConsulta.setAutoCreateRowSorter(true);
        jTConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTConsulta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTConsulta.setForeground(new java.awt.Color(139, 157, 195));
        jTConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Nombre", "Tipo", "Estado"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jTConsulta.setComponentPopupMenu(jPopupMenu1);
        jTConsulta.setGridColor(new java.awt.Color(255, 255, 255));
        jTConsulta.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTConsulta.setRowHeight(25);
        jTConsulta.setSelectionBackground(new java.awt.Color(223, 227, 238));
        jTConsulta.setSelectionForeground(new java.awt.Color(139, 157, 195));
        jScrollPane1.setViewportView(jTConsulta);

        jPBottom.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 40, 712, 224));

        getContentPane().add(jPBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 1368, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit2MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exit2MousePressed
    {//GEN-HEADEREND:event_exit2MousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_exit2MousePressed

    private void exit3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exit3MousePressed
    {//GEN-HEADEREND:event_exit3MousePressed
        new VtnAPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exit3MousePressed

    private void jPTopMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPTopMousePressed
    {//GEN-HEADEREND:event_jPTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPTopMousePressed

    private void jPTopMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPTopMouseDragged
    {//GEN-HEADEREND:event_jPTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPTopMouseDragged

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBGuardarActionPerformed
    {//GEN-HEADEREND:event_jBGuardarActionPerformed
        int valor = 0;
        int tipoEmpleado = evalua(valor);

        String valores1 = ("'" + jTFID.getText() + "',");
        valores1 += ("'" + jCBSucursal.getSelectedItem() + "',");
        valores1 += ("'" + jTFNombre.getText() + "',");
        valores1 += ("'" + jTFAPaterno.getText() + "',");
        valores1 += ("'" + jTFAMaterno.getText() + "',");
        valores1 += ("'" + String.valueOf(jCBSexo.getSelectedItem()) + "',");
        valores1 += ("'" + jTFFechaNac.getText() + "',");
        valores1 += ("'" + jTFCurp.getText() + "',");
        valores1 += ("'" + jTFTelefono.getText() + "',");
        valores1 += ("'" + tipoEmpleado + "',");
        valores1 += ("'" + jTFCorreo.getText() + "',");
        valores1 += ("'" + jPFContra.getText() + "',");
        valores1 += ("'" + jTFFechaAlta.getText() + "'");

        System.out.println("valores ->> " + valores1);
        q = new Querys();

        if (flag)
        {
            String s1 = q.Insertar(con, "empleados", valores1);

            if (s1 != null)
            {
                Mensaje.error(this, s1);
            } else
            {
                Mensaje.exito(this, "Dato insertado correctamente");
            }
        } else
        {
            String columnas = "id_empleado, id_sucursal, nombre, apellido_paterno,"
                    + "apellido_materno, sexo,  fecha_nacimiento, curp, telefono_contacto, tipo_empleado, "
                    + "correo, password, fecha_alta";
            
            String s1 = q.Modificar(con, "empleados", columnas, valores1, "id_empleado = '" + jTFID.getText() + "'");

            Mensaje.exito(this, "Dato modificado correctamente");

            flag = true;
            generaID();
        }

        formWindowOpened(null);
    }//GEN-LAST:event_jBGuardarActionPerformed

    public int evalua(int valor)
    {
        if (String.valueOf(jCBTipoEmple.getSelectedItem()).equals("Gerente"))
        {
            valor = 2;
        } else if (String.valueOf(jCBTipoEmple.getSelectedItem()).equals("Vendedor"))
        {
            valor = 3;
        }
        return valor;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        jBCancelarActionPerformed(null);
        con = ConectarBase.conectaBD();
        generaID();
        cargaComboSucursal();

    }//GEN-LAST:event_formWindowOpened

    private void mostrar()
    {
        DefaultTableModel model = new DefaultTableModel();
        q = new Querys();
        int flag = 0;

        try
        {
            columnaMap2 = q.Seleccion(con, "id_empleado, id_sucursal, nombre, apellido_paterno, apellido_materno", "empleados", "", false);
            model.setColumnIdentifiers(new Object[]
            {
                "ID Empleado", "ID Sucursal", "Nombre", "A. Paterno", "A. Materno"
            });
            while (flag != columnaMap2.size())
            {
                model.addRow(new Object[]
                {
                    columnaMap2.get(flag),
                    columnaMap2.get(flag + 1),
                    columnaMap2.get(flag + 2),
                    columnaMap2.get(flag + 3),
                    columnaMap2.get(flag + 4)

                });
                flag = flag + 5;
            }

            jTConsulta.setModel(model);
            jTConsulta.setValueAt(" " + columnaMap2.get(0), 0, 0);
        } catch (Exception e)
        {
            System.out.println("error --> " + e);
        }
    }

    private void generaID()
    {
        q = new Querys();
        GeneraCodigo gen = new GeneraCodigo();
        String idSucursal;
        try
        {
            columnaMap1 = q.Seleccion(con, "MAX(id_empleado)", "empleados", "", true);
            if (columnaMap1.get(0).equals("null"))
            {
                jTFID.setText("E01");
            } else
            {
                mostrar();
                idSucursal = (String) columnaMap1.get(0);
                gen.generar(Integer.parseInt(idSucursal.substring(1)));
                jTFID.setText("E" + gen.serie());
                jTFID.setEnabled(false);
                CtrlInterfaz.selecciona(jTFNombre);
            }
        } catch (Exception e)
        {
            System.out.println("Error: exception ->" + e);
        }
    }

    private void cargaComboSucursal()
    {
        int contador = 0;
        jCBSucursal.removeAllItems();
        try
        {
            q = new Querys();

            columnaMap1 = q.Seleccion(con, "id_sucursal", "sucursal", "", true);
            while (columnaMap1.size() > contador)
            {
                jCBSucursal.addItem((String) columnaMap1.get(contador));
                contador++;
            }

        } catch (Exception e)
        {
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        ConectarBase.desconectaBD(con);
    }//GEN-LAST:event_formWindowClosed

    private void jTFNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreKeyTyped
    {//GEN-HEADEREND:event_jTFNombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFNombreKeyTyped

    private void jTFNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreKeyPressed
    {//GEN-HEADEREND:event_jTFNombreKeyPressed
        Validaciones.enter(this, evt, jTFAPaterno);
    }//GEN-LAST:event_jTFNombreKeyPressed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBCancelarActionPerformed
    {//GEN-HEADEREND:event_jBCancelarActionPerformed
        CtrlInterfaz.habilita(true, jTFNombre, jBCancelar);
        CtrlInterfaz.habilita(false, jTFID, jTFAPaterno, jTFAMaterno, jCBSucursal,
                jTFFechaNac, jTFCurp, jTFTelefono, jCBTipoEmple, jTFCorreo, jPFContra,
                jTFFechaAlta, jBGuardar, jCBSexo);
        CtrlInterfaz.limpia(jTFID, jTFNombre, jTFAPaterno, jTFAMaterno,
                jTFFechaNac, jTFCurp, jTFTelefono, jTFCorreo, jPFContra,
                jTFFechaAlta);
        generaID();
        flag = true;
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jBGuardarKeyPressed
    {//GEN-HEADEREND:event_jBGuardarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            jBGuardarActionPerformed(null);
        }
    }//GEN-LAST:event_jBGuardarKeyPressed

    private void jTFAPaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAPaternoKeyPressed
    {//GEN-HEADEREND:event_jTFAPaternoKeyPressed
        Validaciones.enter(this, evt, jTFAMaterno);
    }//GEN-LAST:event_jTFAPaternoKeyPressed

    private void jTFAPaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAPaternoKeyTyped
    {//GEN-HEADEREND:event_jTFAPaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFAPaternoKeyTyped

    private void jTFAMaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAMaternoKeyPressed
    {//GEN-HEADEREND:event_jTFAMaternoKeyPressed
        Validaciones.enter(this, evt, jCBSucursal);
    }//GEN-LAST:event_jTFAMaternoKeyPressed

    private void jTFAMaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAMaternoKeyTyped
    {//GEN-HEADEREND:event_jTFAMaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFAMaternoKeyTyped

    private void jTFTelefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyTyped
    {//GEN-HEADEREND:event_jTFTelefonoKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFTelefonoKeyTyped

    private void jTFTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyPressed
    {//GEN-HEADEREND:event_jTFTelefonoKeyPressed
        Validaciones.enter(this, evt, jCBTipoEmple);
    }//GEN-LAST:event_jTFTelefonoKeyPressed

    private void jTFCurpKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCurpKeyTyped
    {//GEN-HEADEREND:event_jTFCurpKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFCurpKeyTyped

    private void jTFCurpKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCurpKeyPressed
    {//GEN-HEADEREND:event_jTFCurpKeyPressed
        Validaciones.enter(this, evt, jTFTelefono);
    }//GEN-LAST:event_jTFCurpKeyPressed

    private void jTFFechaNacKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFFechaNacKeyTyped
    {//GEN-HEADEREND:event_jTFFechaNacKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFFechaNacKeyTyped

    private void jTFFechaNacKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFFechaNacKeyPressed
    {//GEN-HEADEREND:event_jTFFechaNacKeyPressed
        Validaciones.enter(this, evt, jTFCurp);
    }//GEN-LAST:event_jTFFechaNacKeyPressed

    private void jCBSucursalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBSucursalKeyPressed
    {//GEN-HEADEREND:event_jCBSucursalKeyPressed
        Validaciones.enter(this, evt, jCBSexo);
    }//GEN-LAST:event_jCBSucursalKeyPressed

    private void jCBTipoEmpleKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBTipoEmpleKeyPressed
    {//GEN-HEADEREND:event_jCBTipoEmpleKeyPressed
        Validaciones.enter(this, evt, jTFCorreo);
    }//GEN-LAST:event_jCBTipoEmpleKeyPressed

    private void jTFCorreoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCorreoKeyPressed
    {//GEN-HEADEREND:event_jTFCorreoKeyPressed
        Validaciones.enter(this, evt, jPFContra);
    }//GEN-LAST:event_jTFCorreoKeyPressed

    private void jTFCorreoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCorreoKeyTyped
    {//GEN-HEADEREND:event_jTFCorreoKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFCorreoKeyTyped

    private void jTFFechaAltaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFFechaAltaKeyPressed
    {//GEN-HEADEREND:event_jTFFechaAltaKeyPressed
        Validaciones.enter(this, evt, jBGuardar);
    }//GEN-LAST:event_jTFFechaAltaKeyPressed

    private void jTFFechaAltaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFFechaAltaKeyTyped
    {//GEN-HEADEREND:event_jTFFechaAltaKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFFechaAltaKeyTyped

    private void jTFCorreoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTFCorreoActionPerformed
    {//GEN-HEADEREND:event_jTFCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreoActionPerformed

    private void jPFContraKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContraKeyPressed
    {//GEN-HEADEREND:event_jPFContraKeyPressed
        Validaciones.enter(this, evt, jTFFechaAlta);
    }//GEN-LAST:event_jPFContraKeyPressed

    private void jCBSexoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBSexoKeyPressed
    {//GEN-HEADEREND:event_jCBSexoKeyPressed
        Validaciones.enter(this, evt, jTFFechaNac);
    }//GEN-LAST:event_jCBSexoKeyPressed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EliminarActionPerformed
    {//GEN-HEADEREND:event_EliminarActionPerformed
        int filaCelda = jTConsulta.getSelectedRow();
        q = new Querys();
        try
        {
            if (Mensaje.pregunta(this, "¿Esta seguro de eliminar este empleado?") == JOptionPane.YES_OPTION)
            {
                if (filaCelda == -1)
                {
                    Mensaje.error(this, "Selecciona un registro");
                } else
                {
                    try
                    {
                        String cod = (String) jTConsulta.getValueAt(filaCelda, 0);
                        System.out.println(cod + "<-------------Celda a eliminar");
                        q.Delete(con, "empleados", "id_empleado", "'" + cod.substring(1) + "'");
                        Mensaje.exito(this, "Registro Eliminado con exito");
                        formWindowOpened(null);
                        mostrar();
                    } catch (Exception e)
                    {
                        System.out.println("xd");
                        Mensaje.error(this, e.toString());
                    }
                }
            }
        } catch (Exception e)
        {

        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModificarActionPerformed
    {//GEN-HEADEREND:event_ModificarActionPerformed
        try
        {
            if (Mensaje.pregunta(this, "¿Esta seguro de modificar este empleado?") == JOptionPane.YES_OPTION)
            {
                int filaCelda = jTConsulta.getSelectedRow();
                if (filaCelda == -1)
                {
                    Mensaje.error(this, "Selecciona un registro");
                    flag = true;
                } else
                {
                    int cont = 0;
                    jBCancelarActionPerformed(null);

                    String cod = (String) jTConsulta.getValueAt(filaCelda, 0);
                    columnaMap3 = q.Seleccion(con, "*", "empleados", "id_empleado = " + "'" + cod.substring(1) + "'", false);

                    //Mostrar los datos para el modificar
                    jTFID.setText((String) columnaMap3.get(0));

                    cargaComboSucursal();
                    while (cont <= columnaMap1.size())
                    {
                        if (columnaMap1.get(cont).equals(((String) columnaMap3.get(1)).substring(1)))
                        {
                            jCBSucursal.setSelectedIndex(cont);
                            break;
                        } else
                        {
                            cont++;
                        }
                    }

                    jTFNombre.setText(((String) columnaMap3.get(2)).substring(1));
                    jTFAPaterno.setText(((String) columnaMap3.get(3)).substring(1));
                    jTFAMaterno.setText(((String) columnaMap3.get(4)).substring(1));
                    switch ((String) columnaMap3.get(5))
                    {
                        case "M":
                            jCBSexo.setSelectedIndex(0);
                            break;

                        case "F":
                            jCBSexo.setSelectedIndex(1);
                            break;

                        default:
                            System.out.println("Error de opcion");
                    }
                    jTFFechaNac.setText(((String) columnaMap3.get(6)).substring(1));
                    jTFCurp.setText(((String) columnaMap3.get(7)).substring(1));
                    jTFTelefono.setText(((String) columnaMap3.get(8)).substring(1));
                    switch ((String) columnaMap3.get(9))
                    {
                        case "2":
                            jCBTipoEmple.setSelectedIndex(0);
                            break;

                        case "3":
                            jCBTipoEmple.setSelectedIndex(1);
                            break;

                        case "4":
                            jCBTipoEmple.setSelectedIndex(2);
                            break;

                        default:
                            System.out.println("Error de opcion");
                    }
                    jTFCorreo.setText(((String) columnaMap3.get(10)).substring(1));
                    jPFContra.setText(((String) columnaMap3.get(11)).substring(1));
                    jTFFechaAlta.setText(((String) columnaMap3.get(12)).substring(1));

                    flag = false;
                }
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_ModificarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Windows".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new VtnAGestionEmpleados().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel exit3;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<String> jCBSexo;
    private javax.swing.JComboBox<String> jCBSucursal;
    private javax.swing.JComboBox<String> jCBTipoEmple;
    private javax.swing.JLabel jLAPaterno;
    private javax.swing.JLabel jLContra;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaAlta;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLGestion;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLNAMaterno;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLSucursal;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTipoEmple;
    private javax.swing.JPanel jPBottom;
    private javax.swing.JPasswordField jPFContra;
    private javax.swing.JPanel jPMiddle;
    private javax.swing.JPanel jPTop;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSAMaterno;
    private javax.swing.JSeparator jSAPaterno;
    private javax.swing.JSeparator jSContra;
    private javax.swing.JSeparator jSCorreo;
    private javax.swing.JSeparator jSEstado;
    private javax.swing.JSeparator jSFechaAlta;
    private javax.swing.JSeparator jSFechaNac;
    private javax.swing.JSeparator jSNombre;
    private javax.swing.JSeparator jSTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTConsulta;
    private javax.swing.JTextField jTFAMaterno;
    private javax.swing.JTextField jTFAPaterno;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFCurp;
    private javax.swing.JTextField jTFFechaAlta;
    private javax.swing.JTextField jTFFechaNac;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
}
