/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.ConectarBase;
import Clases.GeneraCodigo;
import Clases.Querys;
import static Ventanas.VtnHome.con;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class VtnAGestionSucursal extends javax.swing.JFrame
{

    int xy, xx;
    ArrayList<Object> columnaMap1 = new ArrayList();
    ArrayList<Object> columnaMap2 = new ArrayList();
    ArrayList<Object> columnaMap3 = new ArrayList();
    Querys q;
    boolean flag = true;

    /**
     * Creates new form VtnAGestionSucursal
     */
    public VtnAGestionSucursal()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPAcciones = new javax.swing.JPopupMenu();
        jMNEliminar = new javax.swing.JMenuItem();
        jMNModificar = new javax.swing.JMenuItem();
        jPTop = new javax.swing.JPanel();
        exit2 = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        jLGestion = new javax.swing.JLabel();
        jPMiddle = new javax.swing.JPanel();
        jLID = new javax.swing.JLabel();
        jTFID = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLTipo = new javax.swing.JLabel();
        jCBTipo = new javax.swing.JComboBox<>();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPBottom = new javax.swing.JPanel();
        jLEstado = new javax.swing.JLabel();
        jTFEstado = new javax.swing.JTextField();
        jLMunicipio = new javax.swing.JLabel();
        jTFMunicipio = new javax.swing.JTextField();
        jLCodigoP = new javax.swing.JLabel();
        jTFCodigoP = new javax.swing.JTextField();
        jTFColonia = new javax.swing.JTextField();
        jLColonia = new javax.swing.JLabel();
        jLCalle = new javax.swing.JLabel();
        jTFCalle = new javax.swing.JTextField();
        jLNumero = new javax.swing.JLabel();
        jTFNumero = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jLTelefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsulta = new javax.swing.JTable();
        jSEstado = new javax.swing.JSeparator();
        jSTelefono = new javax.swing.JSeparator();
        jSMunicipio = new javax.swing.JSeparator();
        jSCP = new javax.swing.JSeparator();
        jSMunicipio3 = new javax.swing.JSeparator();
        jSColonia = new javax.swing.JSeparator();
        jSCalle = new javax.swing.JSeparator();
        jSNumero = new javax.swing.JSeparator();

        jMNEliminar.setText("Eliminar");
        jMNEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMNEliminarActionPerformed(evt);
            }
        });
        jPAcciones.add(jMNEliminar);

        jMNModificar.setText("Modificar");
        jMNModificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMNModificarActionPerformed(evt);
            }
        });
        jPAcciones.add(jMNModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPTop.setBackground(new java.awt.Color(255, 255, 255));
        jPTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                jPTopMouseDragged(evt);
            }
        });
        jPTop.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPTopMousePressed(evt);
            }
        });
        jPTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        exit2.setForeground(new java.awt.Color(139, 157, 195));
        exit2.setText("_");
        exit2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                exit2MousePressed(evt);
            }
        });
        jPTop.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1288, 8, 32, 32));

        exit3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit3.setForeground(new java.awt.Color(139, 157, 195));
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                exit3MousePressed(evt);
            }
        });
        jPTop.add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 8, 40, 32));

        jLGestion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLGestion.setForeground(new java.awt.Color(139, 157, 195));
        jLGestion.setText("Gestion de sucursales");
        jPTop.add(jLGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, -1, -1));

        getContentPane().add(jPTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1368, 56));

        jPMiddle.setBackground(new java.awt.Color(139, 157, 195));
        jPMiddle.setForeground(new java.awt.Color(255, 255, 255));
        jPMiddle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLID.setForeground(new java.awt.Color(255, 255, 255));
        jLID.setText("ID: ");
        jPMiddle.add(jLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 32, -1, -1));

        jTFID.setBackground(new java.awt.Color(139, 157, 195));
        jTFID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFID.setForeground(new java.awt.Color(255, 255, 255));
        jTFID.setBorder(null);
        jPMiddle.add(jTFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 32, 121, -1));

        jTFNombre.setBackground(new java.awt.Color(139, 157, 195));
        jTFNombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTFNombre.setBorder(null);
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFNombreKeyTyped(evt);
            }
        });
        jPMiddle.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 72, 224, 24));

        jLNombre.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre: ");
        jPMiddle.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 72, -1, -1));
        jPMiddle.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 96, 224, 16));

        jLTipo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLTipo.setText("Tipo: ");
        jPMiddle.add(jLTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 120, -1, -1));

        jCBTipo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCBTipo.setForeground(new java.awt.Color(139, 157, 195));
        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primaria", "Secundaria" }));
        jCBTipo.setBorder(null);
        jCBTipo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jCBTipoKeyPressed(evt);
            }
        });
        jPMiddle.add(jCBTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 118, 224, 24));

        jBGuardar.setBackground(new java.awt.Color(247, 247, 247));
        jBGuardar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(139, 157, 195));
        jBGuardar.setText("Guardar");
        jBGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 227, 238)));
        jBGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBGuardarActionPerformed(evt);
            }
        });
        jBGuardar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jBGuardarKeyPressed(evt);
            }
        });
        jPMiddle.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1096, 64, 88, 32));

        jBCancelar.setBackground(new java.awt.Color(247, 247, 247));
        jBCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(139, 157, 195));
        jBCancelar.setText("Cancelar");
        jBCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 227, 238)));
        jBCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBCancelarActionPerformed(evt);
            }
        });
        jPMiddle.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1208, 64, 88, 32));

        getContentPane().add(jPMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 1368, 168));

        jPBottom.setBackground(new java.awt.Color(255, 255, 255));
        jPBottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLEstado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(139, 157, 195));
        jLEstado.setText("Estado: ");
        jPBottom.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 24, -1, -1));

        jTFEstado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFEstado.setForeground(new java.awt.Color(139, 157, 195));
        jTFEstado.setBorder(null);
        jTFEstado.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFEstadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFEstadoKeyTyped(evt);
            }
        });
        jPBottom.add(jTFEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 24, 208, -1));

        jLMunicipio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLMunicipio.setForeground(new java.awt.Color(139, 157, 195));
        jLMunicipio.setText("Municipio: ");
        jPBottom.add(jLMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 56, -1, -1));

        jTFMunicipio.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFMunicipio.setForeground(new java.awt.Color(139, 157, 195));
        jTFMunicipio.setBorder(null);
        jTFMunicipio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFMunicipioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFMunicipioKeyTyped(evt);
            }
        });
        jPBottom.add(jTFMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 56, 208, -1));

        jLCodigoP.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLCodigoP.setForeground(new java.awt.Color(139, 157, 195));
        jLCodigoP.setText("Codigo postal: ");
        jPBottom.add(jLCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 88, -1, -1));

        jTFCodigoP.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFCodigoP.setForeground(new java.awt.Color(139, 157, 195));
        jTFCodigoP.setBorder(null);
        jTFCodigoP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFCodigoPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFCodigoPKeyTyped(evt);
            }
        });
        jPBottom.add(jTFCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 88, 208, -1));

        jTFColonia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFColonia.setForeground(new java.awt.Color(139, 157, 195));
        jTFColonia.setBorder(null);
        jTFColonia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFColoniaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFColoniaKeyTyped(evt);
            }
        });
        jPBottom.add(jTFColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 120, 208, -1));

        jLColonia.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLColonia.setForeground(new java.awt.Color(139, 157, 195));
        jLColonia.setText("Colonia: ");
        jPBottom.add(jLColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 120, -1, -1));

        jLCalle.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLCalle.setForeground(new java.awt.Color(139, 157, 195));
        jLCalle.setText("Calle: ");
        jPBottom.add(jLCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 152, -1, -1));

        jTFCalle.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFCalle.setForeground(new java.awt.Color(139, 157, 195));
        jTFCalle.setBorder(null);
        jTFCalle.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFCalleKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFCalleKeyTyped(evt);
            }
        });
        jPBottom.add(jTFCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 152, 208, -1));

        jLNumero.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLNumero.setForeground(new java.awt.Color(139, 157, 195));
        jLNumero.setText("Numero: ");
        jPBottom.add(jLNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 184, -1, -1));

        jTFNumero.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFNumero.setForeground(new java.awt.Color(139, 157, 195));
        jTFNumero.setBorder(null);
        jTFNumero.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFNumeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFNumeroKeyTyped(evt);
            }
        });
        jPBottom.add(jTFNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 184, 208, -1));

        jTFTelefono.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(139, 157, 195));
        jTFTelefono.setBorder(null);
        jTFTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFTelefonoKeyTyped(evt);
            }
        });
        jPBottom.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 216, 208, -1));

        jLTelefono.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLTelefono.setForeground(new java.awt.Color(139, 157, 195));
        jLTelefono.setText("Teléfono: ");
        jPBottom.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 216, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTConsulta.setAutoCreateRowSorter(true);
        jTConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTConsulta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTConsulta.setForeground(new java.awt.Color(139, 157, 195));
        jTConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Nombre", "Tipo", "Estado"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jTConsulta.setComponentPopupMenu(jPAcciones);
        jTConsulta.setGridColor(new java.awt.Color(255, 255, 255));
        jTConsulta.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTConsulta.setRowHeight(25);
        jTConsulta.setSelectionBackground(new java.awt.Color(223, 227, 238));
        jTConsulta.setSelectionForeground(new java.awt.Color(139, 157, 195));
        jScrollPane1.setViewportView(jTConsulta);
        if (jTConsulta.getColumnModel().getColumnCount() > 0)
        {
            jTConsulta.getColumnModel().getColumn(0).setResizable(false);
            jTConsulta.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTConsulta.getColumnModel().getColumn(1).setResizable(false);
            jTConsulta.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTConsulta.getColumnModel().getColumn(2).setResizable(false);
            jTConsulta.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTConsulta.getColumnModel().getColumn(3).setResizable(false);
            jTConsulta.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jPBottom.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 40, 712, 224));

        jSEstado.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 48, 208, 16));

        jSTelefono.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 240, 208, 16));

        jSMunicipio.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 80, 208, 16));

        jSCP.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 112, 208, 16));

        jSMunicipio3.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSMunicipio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 120, 128, 16));

        jSColonia.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 144, 208, 16));

        jSCalle.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 176, 208, 16));

        jSNumero.setBackground(new java.awt.Color(139, 157, 195));
        jPBottom.add(jSNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 208, 208, 16));

        getContentPane().add(jPBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 1376, 528));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit2MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exit2MousePressed
    {//GEN-HEADEREND:event_exit2MousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_exit2MousePressed

    private void exit3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exit3MousePressed
    {//GEN-HEADEREND:event_exit3MousePressed
        new VtnAPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exit3MousePressed

    private void jPTopMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPTopMousePressed
    {//GEN-HEADEREND:event_jPTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPTopMousePressed

    private void jPTopMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPTopMouseDragged
    {//GEN-HEADEREND:event_jPTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPTopMouseDragged

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBGuardarActionPerformed
    {//GEN-HEADEREND:event_jBGuardarActionPerformed
        String direccion = jTFMunicipio.getText() + "-" + jTFCodigoP.getText() + "-" + jTFColonia.getText()
                + "-" + jTFCalle.getText() + "-" + jTFNumero.getText();
        int tipoSucu = 0;
        switch ((String) jCBTipo.getSelectedItem())
        {
            case "Primaria":
                tipoSucu = 1;
                break;
            case "Secundaria":
                tipoSucu = 2;
                break;
            default:
                System.out.println("No existe ese tipo de sucursal --->" + (String) jCBTipo.getSelectedItem());
        }

        String valores1 = ("'" + jTFID.getText()) + "',";
        valores1 += ("'" + jTFNombre.getText() + "',");
        valores1 += ("'" + tipoSucu + "',");
        valores1 += ("'" + jTFEstado.getText() + "',");
        valores1 += ("'" + direccion + "',");
        valores1 += ("'" + jTFTelefono.getText() + "'");

        q = new Querys();

        if (flag)
        {
            String sl = q.Insertar(con, "sucursal", valores1);

            if (sl != null)
            {
                Mensaje.error(this, sl);
            } else
            {
                Mensaje.exito(this, "Dato insertado correctamente");
            }
            flag = true;
            generaID();
        } else
        {
            String columnas = "id_sucursal, nombre_sucursal, tipo, estado, direccion, telefono";
            String s1 = q.Modificar(con, "sucursal", columnas, valores1, "id_sucursal = '" + jTFID.getText() + "'");

            Mensaje.exito(this, "Dato modificado correctamente");

            flag = true;
            generaID();
        }

        jBCancelarActionPerformed(evt);
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        jBCancelarActionPerformed(null);
        con = ConectarBase.conectaBD();
        generaID();
    }//GEN-LAST:event_formWindowOpened

    private void generaID()
    {
        q = new Querys();
        GeneraCodigo gen = new GeneraCodigo();
        String idSucursal;

        try
        {
            columnaMap1 = q.Seleccion(con, "MAX(id_sucursal)", "sucursal", "", true);
            if (columnaMap1.get(0).equals("null"))
            {
                jTFID.setText("S01");
            } else 
            {
                mostrar();
                idSucursal = (String) columnaMap1.get(0);
                gen.generar(Integer.parseInt(idSucursal.substring(1)));
                jTFID.setText("S" + gen.serie());
                jTFID.setEnabled(false);
                CtrlInterfaz.selecciona(jTFNombre);
            }
        } catch (Exception e)
        {
            System.out.println("Error: exception ->" + e);
        }
        
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        ConectarBase.desconectaBD(con);
    }//GEN-LAST:event_formWindowClosed

    private void jTFNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreKeyTyped
    {//GEN-HEADEREND:event_jTFNombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFNombreKeyTyped

    private void jTFNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreKeyPressed
    {//GEN-HEADEREND:event_jTFNombreKeyPressed
        Validaciones.enter(this, evt, jCBTipo);
    }//GEN-LAST:event_jTFNombreKeyPressed

    private void jCBTipoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBTipoKeyPressed
    {//GEN-HEADEREND:event_jCBTipoKeyPressed
        Validaciones.enter(this, evt, jTFEstado);
    }//GEN-LAST:event_jCBTipoKeyPressed

    private void jTFEstadoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFEstadoKeyTyped
    {//GEN-HEADEREND:event_jTFEstadoKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFEstadoKeyTyped

    private void jTFEstadoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFEstadoKeyPressed
    {//GEN-HEADEREND:event_jTFEstadoKeyPressed
        Validaciones.enter(this, evt, jTFMunicipio);
    }//GEN-LAST:event_jTFEstadoKeyPressed

    private void jTFMunicipioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFMunicipioKeyTyped
    {//GEN-HEADEREND:event_jTFMunicipioKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFMunicipioKeyTyped

    private void jTFMunicipioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFMunicipioKeyPressed
    {//GEN-HEADEREND:event_jTFMunicipioKeyPressed
        Validaciones.enter(this, evt, jTFCodigoP);
    }//GEN-LAST:event_jTFMunicipioKeyPressed

    private void jTFCodigoPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCodigoPKeyTyped
    {//GEN-HEADEREND:event_jTFCodigoPKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jTFCodigoPKeyTyped

    private void jTFCodigoPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCodigoPKeyPressed
    {//GEN-HEADEREND:event_jTFCodigoPKeyPressed
        Validaciones.enter(this, evt, jTFColonia);
    }//GEN-LAST:event_jTFCodigoPKeyPressed

    private void jTFColoniaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFColoniaKeyTyped
    {//GEN-HEADEREND:event_jTFColoniaKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFColoniaKeyTyped

    private void jTFColoniaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFColoniaKeyPressed
    {//GEN-HEADEREND:event_jTFColoniaKeyPressed
        Validaciones.enter(this, evt, jTFCalle);
    }//GEN-LAST:event_jTFColoniaKeyPressed

    private void jTFCalleKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCalleKeyTyped
    {//GEN-HEADEREND:event_jTFCalleKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFCalleKeyTyped

    private void jTFCalleKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCalleKeyPressed
    {//GEN-HEADEREND:event_jTFCalleKeyPressed
        Validaciones.enter(this, evt, jTFNumero);
    }//GEN-LAST:event_jTFCalleKeyPressed

    private void jTFNumeroKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNumeroKeyTyped
    {//GEN-HEADEREND:event_jTFNumeroKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jTFNumeroKeyTyped

    private void jTFNumeroKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNumeroKeyPressed
    {//GEN-HEADEREND:event_jTFNumeroKeyPressed
        Validaciones.enter(this, evt, jTFTelefono);
    }//GEN-LAST:event_jTFNumeroKeyPressed

    private void jTFTelefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyTyped
    {//GEN-HEADEREND:event_jTFTelefonoKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jTFTelefonoKeyTyped

    private void jTFTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyPressed
    {//GEN-HEADEREND:event_jTFTelefonoKeyPressed
        Validaciones.enter(this, evt, jBGuardar);
    }//GEN-LAST:event_jTFTelefonoKeyPressed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBCancelarActionPerformed
    {//GEN-HEADEREND:event_jBCancelarActionPerformed
        CtrlInterfaz.habilita(true, jTFNombre, jBCancelar);
        CtrlInterfaz.habilita(false, jTFID, jCBTipo, jTFEstado, jTFMunicipio, jTFCodigoP,
                jTFColonia, jTFCalle, jTFNumero, jTFTelefono, jBGuardar);
        CtrlInterfaz.limpia(jTFNombre, jTFEstado, jTFMunicipio, jTFCodigoP,
                jTFColonia, jTFCalle, jTFNumero, jTFTelefono);
        generaID();
        flag = true;
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jBGuardarKeyPressed
    {//GEN-HEADEREND:event_jBGuardarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            jBGuardarActionPerformed(null);
        }
    }//GEN-LAST:event_jBGuardarKeyPressed

    private void jMNModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMNModificarActionPerformed
    {//GEN-HEADEREND:event_jMNModificarActionPerformed
        try
        {
            if (Mensaje.pregunta(this, "¿Esta seguro de modificar esta sucursal?") == JOptionPane.YES_OPTION)
            {
                int filaCelda = jTConsulta.getSelectedRow();
                if (filaCelda == -1)
                {
                    Mensaje.error(this, "Selecciona un registro");
                    flag = true;
                } else
                {
                    jBCancelarActionPerformed(null);

                    String cod = (String) jTConsulta.getValueAt(filaCelda, 0);
                    columnaMap3 = q.Seleccion(con, "*", "sucursal", "id_sucursal = " + "'" + cod.substring(1) + "'", false);

                    //Mostrar los datos para el modificar
                    jTFID.setText((String) columnaMap3.get(0));
                    jTFNombre.setText(((String) columnaMap3.get(1)).substring(1));
                    switch ((String) columnaMap3.get(2))
                    {
                        case "1":
                            jCBTipo.setSelectedIndex(0);
                            break;

                        case "2":
                            jCBTipo.setSelectedIndex(1);
                            break;

                        default:
                            System.out.println("Error de opcion");
                    }
                    jTFEstado.setText(((String) columnaMap3.get(3)).substring(1));

                    StringTokenizer st = new StringTokenizer((String) columnaMap3.get(4), "-");

                    while (st.hasMoreTokens())
                    {

                        jTFMunicipio.setText(st.nextToken().substring(1));
                        jTFCodigoP.setText(st.nextToken());
                        jTFColonia.setText(st.nextToken());
                        jTFCalle.setText(st.nextToken());
                        jTFNumero.setText(st.nextToken());

                    }

                    jTFTelefono.setText(((String) columnaMap3.get(5)).substring(1));
                    CtrlInterfaz.habilita(false, jTFNombre);
                    CtrlInterfaz.habilita(true, jTFEstado);
                    flag = false;
                }
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_jMNModificarActionPerformed

    private void jMNEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMNEliminarActionPerformed
    {//GEN-HEADEREND:event_jMNEliminarActionPerformed
        int filaCelda = jTConsulta.getSelectedRow();
        q = new Querys();
        try
        {
            if (Mensaje.pregunta(this, "¿Esta seguro de eliminar esta sucursal?") == JOptionPane.YES_OPTION)
            {
                if (filaCelda == -1)
                {
                    Mensaje.error(this, "Selecciona un registro");
                } else
                {
                    try
                    {
                        String cod = (String) jTConsulta.getValueAt(filaCelda, 0);
                        System.out.println(cod + "<-------------Celda a eliminar");
                        q.Delete(con, "sucursal", "id_sucursal", "'" + cod.substring(1) + "'");
                        Mensaje.exito(this, "Registro Eliminado con exito");
                        formWindowOpened(null);
                        mostrar();
                    } catch (Exception e)
                    {
                        System.out.println("xd");
                        Mensaje.error(this, e.toString());
                    }
                }
            }
        } catch (Exception e)
        {

        }
    }//GEN-LAST:event_jMNEliminarActionPerformed

    private void mostrar()
    {
        DefaultTableModel model = new DefaultTableModel();
        q = new Querys();
        int flag = 0;

        try
        {
            columnaMap2 = q.Seleccion(con, "id_sucursal, nombre_sucursal, tipo, estado", "sucursal", "", false);
            model.setColumnIdentifiers(new Object[]
            {
                "ID", "Nombre", "Tipo", "Estado"
            });
            while (flag != columnaMap2.size())
            {
                model.addRow(new Object[]
                {
                    columnaMap2.get(flag),
                    columnaMap2.get(flag + 1),
                    columnaMap2.get(flag + 2),
                    columnaMap2.get(flag + 3)
                });
                flag = flag + 4;
            }

            jTConsulta.setModel(model);
            jTConsulta.setValueAt(" " + columnaMap2.get(0), 0, 0);
        } catch (Exception e)
        {
            System.out.println("error --> " + e);
        }

    }

    private void buscaRegistro(String cod)
    {
        try
        {
            q = new Querys();
            try
            {
                columnaMap3 = q.Seleccion(con, "*", "sucursal", "id_sucursal='" + cod.substring(1) + "'", true);
            } catch (Exception e)
            {
                System.out.println("error --> " + e);
            }

            String direccion;

            jTFID.setText((String) columnaMap3.get(0));
            jTFNombre.setText((String) columnaMap3.get(1));
            jCBTipo.setSelectedIndex((int) columnaMap3.get(2) - 1);
            jTFEstado.setText((String) columnaMap3.get(3));

        } catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Windows".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(VtnAGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new VtnAGestionSucursal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel exit3;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JLabel jLCalle;
    private javax.swing.JLabel jLCodigoP;
    private javax.swing.JLabel jLColonia;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLGestion;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLMunicipio;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JMenuItem jMNEliminar;
    private javax.swing.JMenuItem jMNModificar;
    private javax.swing.JPopupMenu jPAcciones;
    private javax.swing.JPanel jPBottom;
    private javax.swing.JPanel jPMiddle;
    private javax.swing.JPanel jPTop;
    private javax.swing.JSeparator jSCP;
    private javax.swing.JSeparator jSCalle;
    private javax.swing.JSeparator jSColonia;
    private javax.swing.JSeparator jSEstado;
    private javax.swing.JSeparator jSMunicipio;
    private javax.swing.JSeparator jSMunicipio3;
    private javax.swing.JSeparator jSNumero;
    private javax.swing.JSeparator jSTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTConsulta;
    private javax.swing.JTextField jTFCalle;
    private javax.swing.JTextField jTFCodigoP;
    private javax.swing.JTextField jTFColonia;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFMunicipio;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
}
